name: Testing

on:
  push:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check format
      run: black --check --verbose .
    - name: Run Tests
      env:
        SECRET_KEY: super_secret_key
        ACCESS_TOKEN_EXPIRE_MINUTES_DEFAULT: 60
        MIN_PASSWORD_LENGHT: 1
        MAX_PASSWORD_LENGHT: 200
        DATABASE_NAME: postgres
        DATABASE_USER: postgres
        DATABASE_PASSWORD: postgres
        DATABASE_HOST: localhost
        DATABASE_PORT: 5432
        PORT: 8000
      run: |
        pytest .